import os
import time
import hmac
import hashlib
import json
import base64
import logging
import asyncio
import re
from datetime import datetime
from typing import Optional, Dict, Any, List, Tuple
from pathlib import Path

import httpx
from anthropic import Anthropic
from fastapi import FastAPI, Request, HTTPException
from fastapi.responses import JSONResponse, PlainTextResponse

# ----------------------------
# App + Logging
# ----------------------------
app = FastAPI()
logger = logging.getLogger("uvicorn.error")

# ----------------------------
# Env Vars — existing
# ----------------------------
SLACK_SIGNING_SECRET = os.getenv("SLACK_SIGNING_SECRET", "")
SLACK_BOT_TOKEN = os.getenv("SLACK_BOT_TOKEN", "")
SLACK_DEFAULT_CHANNEL = os.getenv("SLACK_DEFAULT_CHANNEL", "")
BART_USER_ID = os.getenv("BART_USER_ID", "")

ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY", "")
CLAUDE_MODEL = os.getenv("CLAUDE_MODEL", "claude-3-5-sonnet-latest")
anthropic_client = Anthropic(api_key=ANTHROPIC_API_KEY) if ANTHROPIC_API_KEY else None

SLACK_API_BASE = "https://slack.com/api"

# ----------------------------
# Env Vars — new
# ----------------------------
SEM_LP_REQUESTS_CHANNEL = os.getenv("SEM_LP_REQUESTS_CHANNEL", "")   # private channel with BartBot
SEM_LP_BUILD_KITS_CHANNEL = os.getenv("SEM_LP_BUILD_KITS_CHANNEL", "")  # agency-facing results channel
GITHUB_TOKEN = os.getenv("GITHUB_TOKEN", "")
GITHUB_REPO = os.getenv("GITHUB_REPO", "")
GITHUB_BRANCH = os.getenv("GITHUB_BRANCH", "main")

# ----------------------------
# Job state — persisted to disk so restarts don't lose in-flight jobs
# Keyed by bart_thread_ts (the thread in the private Bart channel)
# ----------------------------
JOBS_FILE = Path("jobs.json")

def _load_jobs() -> Dict[str, Dict[str, Any]]:
    try:
        return json.loads(JOBS_FILE.read_text(encoding="utf-8"))
    except Exception:
        return {}

def _save_jobs() -> None:
    try:
        JOBS_FILE.write_text(json.dumps(JOBS, indent=2), encoding="utf-8")
    except Exception as e:
        logger.warning("Could not save jobs.json: %s", e)

JOBS: Dict[str, Dict[str, Any]] = _load_jobs()

# ----------------------------
# Repo doc loading
# ----------------------------
def load_text(path: str, max_chars: int) -> str:
    try:
        txt = Path(path).read_text(encoding="utf-8")
        return txt[:max_chars]
    except Exception as e:
        logger.warning("Could not load %s: %s", path, e)
        return f"[Missing file: {path}]"

# Existing docs
SEM_STRUCTURE = load_text("SEM-LP-Structure.md", 18000)
SEO_RULES = load_text("SEO-Best-Practices.md", 14000)
EDITORIAL_STYLE = load_text("datahub-editorial-style.md", 14000)
GARTNER_SNIPPETS = load_text("datahub-gartner-peer-insights.md", 9000)
BRAND_GUIDELINES = load_text("brand-guidelines.md", 14000)
HTML_TEMPLATE = load_text("datahub-observability-final.html", 20000)

# DataHub brand system docs
BRAND_SKILL_MD = load_text(".claude/skills/front-end-design/SKILL.md", 22000)
SAMPLE_LP_HTML = load_text("templates/datahub-governance-lp1.html", 28000)
BRAND_VOICE_MD = load_text("docs/brand-voice.md", 8000)

# Extract the full <style> block and <head> from the template at startup.
# Claude only generates the <body> — we assemble the full page in code.
_style_match = re.search(r'<style[\s\S]*?</style>', SAMPLE_LP_HTML, re.IGNORECASE)
_raw_css = _style_match.group(0) if _style_match else ""
# Make is-hidden visible so content shows without JS
TEMPLATE_CSS = _raw_css.replace(
    ".animate-in.is-hidden { opacity: 0; transform: translateY(24px); }",
    ".animate-in.is-hidden { opacity: 1; transform: none; }"
).replace(
    ".animate-in.is-hidden{opacity:0;transform:translateY(24px)}",
    ".animate-in.is-hidden{opacity:1;transform:none}"
)

# Hardcoded trust strip — always injected verbatim, never generated by Claude
TRUST_STRIP_HTML = """<!-- ── LOGO SCROLLER ─────────────────────────────────────────── -->
<section class="logo-scroller" aria-label="Trusted by">
  <div class="logo-scroller-label">Trusted by modern data teams</div>
  <div class="marquee" aria-hidden="true">
    <div class="marquee-track">
      <span class="marquee-item">Netflix</span><span class="marquee-item">Visa</span><span class="marquee-item">Slack</span><span class="marquee-item">Notion</span><span class="marquee-item">Chime</span><span class="marquee-item">Pinterest</span><span class="marquee-item">MYOB</span><span class="marquee-item">Airtel</span><span class="marquee-item">DoorDash</span><span class="marquee-item">Etsy</span><span class="marquee-item">Deutsche Telekom</span><span class="marquee-item">Twilio</span>
      <span class="marquee-item">Netflix</span><span class="marquee-item">Visa</span><span class="marquee-item">Slack</span><span class="marquee-item">Notion</span><span class="marquee-item">Chime</span><span class="marquee-item">Pinterest</span><span class="marquee-item">MYOB</span><span class="marquee-item">Airtel</span><span class="marquee-item">DoorDash</span><span class="marquee-item">Etsy</span><span class="marquee-item">Deutsche Telekom</span><span class="marquee-item">Twilio</span>
    </div>
  </div>
</section>"""

# Logo SVG loaded at startup — committed with every generated page
LOGO_SVG_BLACK = load_text("templates/dataHub_logo_color_black.svg", 50000)

# Footer + scripts extracted from template — injected verbatim if Claude truncates
_footer_match = re.search(r'<!-- ── FOOTER[\s\S]*?</script>', SAMPLE_LP_HTML, re.IGNORECASE)
TEMPLATE_FOOTER_HTML = _footer_match.group(0) if _footer_match else ""

# GitHub Pages base URL — derived from GITHUB_REPO at startup
_repo_parts = GITHUB_REPO.split("/", 1)
GITHUB_PAGES_BASE = (
    f"https://{_repo_parts[0]}.github.io/{_repo_parts[1]}"
    if len(_repo_parts) == 2 and all(_repo_parts) else ""
)

def build_page_head(title: str, meta_description: str) -> str:
    """Build the full <head> with correct title/meta and the template CSS."""
    return f"""<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="{meta_description}">
<title>{title}</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Castoro:ital@0;1&family=Geist:wght@300;400;500;600&display=swap" rel="stylesheet">
{TEMPLATE_CSS}
</head>"""

# ----------------------------
# Slack signature verification
# ----------------------------
def verify_slack_signature(raw_body: bytes, timestamp: str, signature: str) -> None:
    if not SLACK_SIGNING_SECRET:
        raise HTTPException(status_code=500, detail="Missing SLACK_SIGNING_SECRET")
    if not timestamp or not signature:
        raise HTTPException(status_code=400, detail="Missing Slack signature headers")
    now = int(time.time())
    try:
        ts = int(timestamp)
    except Exception:
        raise HTTPException(status_code=400, detail="Invalid X-Slack-Request-Timestamp")
    if abs(now - ts) > 60 * 5:
        raise HTTPException(status_code=400, detail="Stale Slack request (possible replay)")
    basestring = f"v0:{timestamp}:".encode("utf-8") + raw_body
    expected = "v0=" + hmac.new(
        SLACK_SIGNING_SECRET.encode("utf-8"), basestring, hashlib.sha256
    ).hexdigest()
    if not hmac.compare_digest(expected, signature):
        raise HTTPException(status_code=401, detail="Invalid Slack signature")

# ----------------------------
# Slack helpers
# ----------------------------
async def slack_api(method: str, payload: Dict[str, Any]) -> Dict[str, Any]:
    if not SLACK_BOT_TOKEN:
        raise HTTPException(status_code=500, detail="Missing SLACK_BOT_TOKEN")
    url = f"{SLACK_API_BASE}/{method}"
    async with httpx.AsyncClient(timeout=20) as client:
        resp = await client.post(
            url,
            headers={"Authorization": f"Bearer {SLACK_BOT_TOKEN}"},
            json=payload,
        )
    data = resp.json()
    if not data.get("ok"):
        raise HTTPException(status_code=500, detail=f"Slack API {method} failed: {data}")
    return data

async def post_message(channel: str, text: str, thread_ts: Optional[str] = None) -> str:
    payload: Dict[str, Any] = {"channel": channel, "text": text}
    if thread_ts:
        payload["thread_ts"] = thread_ts
    data = await slack_api("chat.postMessage", payload)
    return data.get("ts")

# ----------------------------
# General helpers
# ----------------------------
def generate_request_id() -> str:
    return datetime.now().strftime("LP-%Y%m%d-%H%M")

def slugify(text: str, max_len: int = 50) -> str:
    t = (text or "").strip().lower()
    t = "-".join(t.split())
    cleaned = [ch for ch in t if ch.isalnum() or ch == "-"]
    out = "".join(cleaned)
    return out[:max_len] if len(out) > max_len else out

def safe_truncate(s: str, n: int = 3500) -> str:
    return s if len(s) <= n else s[:n] + "\n...(truncated)"

def parse_secondary_keywords(raw: Optional[str]) -> List[str]:
    if not raw:
        return []
    raw = raw.replace(",", "\n")
    out: List[str] = []
    seen = set()
    for line in raw.splitlines():
        k = line.strip()
        if not k:
            continue
        lk = k.lower()
        if lk in seen:
            continue
        seen.add(lk)
        out.append(k)
    return out

# ----------------------------
# Thread accumulation
# ----------------------------
async def fetch_thread_messages(channel: str, thread_ts: str) -> List[Dict[str, Any]]:
    try:
        url = f"{SLACK_API_BASE}/conversations.replies"
        async with httpx.AsyncClient(timeout=20) as client:
            resp = await client.get(
                url,
                headers={"Authorization": f"Bearer {SLACK_BOT_TOKEN}"},
                params={"channel": channel, "ts": thread_ts, "limit": "200"},
            )
        data = resp.json()
        if not data.get("ok"):
            logger.warning("conversations.replies failed channel=%s ts=%s error=%s", channel, thread_ts, data)
            return []
        return data.get("messages", [])
    except Exception as e:
        logger.warning("Could not fetch thread %s: %s", thread_ts, e)
        return []

def accumulate_bart_brief(messages: List[Dict[str, Any]], bart_user_id: str) -> str:
    parts = [
        (msg.get("text") or "").strip()
        for msg in messages
        if msg.get("user") == bart_user_id and (msg.get("text") or "").strip()
    ]
    return "\n\n---\n\n".join(parts) if parts else ""

# ----------------------------
# Image reference parsing
# ----------------------------
def parse_image_refs(bart_brief: str) -> List[Dict[str, str]]:
    images: List[Dict[str, str]] = []
    seen: set = set()
    for alt, path in re.findall(
        r'!\[([^\]]*)\]\(([^)]+\.(?:png|jpg|jpeg))\)', bart_brief, re.IGNORECASE
    ):
        name = Path(path).name
        if name not in seen:
            seen.add(name)
            images.append({"filename": name, "description": alt, "path": path})
    for name in re.findall(r'\b([\w-]+\.png)\b', bart_brief, re.IGNORECASE):
        if name not in seen:
            seen.add(name)
            images.append({
                "filename": name,
                "description": name.replace("-", " ").replace(".png", ""),
                "path": f"images/{name}",
            })
    return images

# ----------------------------
# SVG generation
# ----------------------------
def build_svg_prompt(image_info: Dict[str, str], bart_brief: str, slug: str) -> str:
    fname = image_info["filename"].lower()
    if "workflow" in fname or "process" in fname or "policy" in fname:
        diagram_type = "Explainer (horizontal workflow)"
        viewbox = "0 0 960 540"
    elif "ui" in fname or "screenshot" in fname:
        diagram_type = "Stylized UI"
        viewbox = "0 0 960 680"
    else:
        diagram_type = "Explainer (architecture)"
        viewbox = "0 0 960 680"

    svg_name = image_info["filename"].replace(".png", ".svg")
    return f"""You are operating in SVG Conversion Mode from the DataHub brand system.

[DATAHUB BRAND SYSTEM]
{BRAND_SKILL_MD}

[SOURCE BRIEF — source of truth for diagram content]
{bart_brief[:6000]}

Task: Generate a brand-compliant DataHub SVG illustration for the following image.

Image reference:
- Original filename: {image_info["filename"]}
- Description: {image_info["description"]}
- Diagram type: {diagram_type}
- Output filename: {svg_name}
- Page slug: {slug}

SVG requirements (non-negotiable):
- Opening tag: <svg xmlns="http://www.w3.org/2000/svg" viewBox="{viewbox}" role="img">
- Must include <title> and <desc> elements immediately after the opening tag
- Import Castoro + Geist from Google Fonts inside a <defs><style> block
- Brand colors only: #002131, #0A4170, #3CBBEB, #B0EAFC, #F2F1EE, #1E1E1E, #767473
- Minimum font-size attribute: 9 — no text below this value
- Flat tile-and-frame layout; no drop shadows, gradients, or glow
- Arrow markers using fill="#3CBBEB"
- Page background: <rect width="100%" height="100%" fill="#F2F1EE"/>

Run the SVG Conversion QA Checklist from the brand system before outputting.

Return ONLY the complete SVG markup — starting with <svg and ending with </svg>.
No code fences, no explanation, no preamble.
""".strip()

async def generate_svgs(bart_brief: str, slug: str) -> Dict[str, str]:
    image_refs = parse_image_refs(bart_brief)
    if not image_refs:
        return {}

    async def gen_one(img_info: Dict[str, str]) -> Tuple[str, str]:
        prompt = build_svg_prompt(img_info, bart_brief, slug)
        try:
            svg_content = await claude_text(prompt, max_tokens=4500)
            match = re.search(r'<svg[\s\S]*?</svg>', svg_content, re.DOTALL)
            if match:
                svg_content = match.group(0)
            svg_name = img_info["filename"].replace(".png", ".svg")
            return svg_name, svg_content
        except Exception as e:
            logger.warning("SVG generation failed for %s: %s", img_info["filename"], e)
            return img_info["filename"].replace(".png", ".svg"), ""

    results = await asyncio.gather(*[gen_one(img) for img in image_refs])
    return {name: content for name, content in results if content}

# ----------------------------
# LP package generation
# ----------------------------
def _hubspot_form_id(cta_type: str) -> str:
    return {
        "Demo": "ed2447d6-e6f9-4771-8f77-825b114a9421",
        "Free Trial": "42182785-f711-40b4-92e7-11468579321b",
        "Bi-weekly Demo": "2bf16106-3e8e-4dc3-9ae4-5b0bce901d88",
        "Product Tour": "aa56e90c-044a-46d8-a92f-cb905ad662f8",
    }.get(cta_type, "ed2447d6-e6f9-4771-8f77-825b114a9421")

def build_copywriter_prompt(fields: dict, bart_brief: str, secondary_keywords: List[str]) -> str:
    secondary_block = (
        "\n".join(f"- {k}" for k in secondary_keywords) if secondary_keywords else "(none)"
    )
    form_id = _hubspot_form_id(fields.get("primary_cta", "Demo"))
    cta = fields.get("primary_cta", "Demo")
    return f"""You are a conversion copywriter for DataHub SEM landing pages. Your job is to transform a validated technical brief into persuasive page copy that earns scrolls and form fills.

HARD CONSTRAINTS — follow these documents exactly:

[SEM PAGE STRUCTURE — section order is mandatory]
{SEM_STRUCTURE}

[SEO BEST PRACTICES]
{SEO_RULES}

[BRAND VOICE]
{BRAND_VOICE_MD}

[EDITORIAL STYLE]
{EDITORIAL_STYLE}

[GARTNER PEER INSIGHTS — use sparingly, never fabricate]
{GARTNER_SNIPPETS}

Campaign inputs:
- Primary keyword (exact, verbatim): "{fields["search_term"]}"
- Secondary keywords:
{secondary_block}
- Primary CTA: "{cta}"
- Intent: "{fields.get("intent","Commercial")}"
- Primary audience: "{fields.get("primary_audience","")}"
- Offer: "{fields.get("offer","")}"
- Must include: "{fields.get("must_include","")}"
- Must not say: "{fields.get("must_not_say","")}"

BART_VALIDATED_OUTPUT — only use claims that appear here:
{bart_brief[:8000]}

━━━ CONVERSION COPYWRITING RULES ━━━

COGNITIVE BIAS — apply these deliberately, section by section:

Loss aversion (Problem section):
- Lead with the cost of inaction, not just the pain point
- Make the risk concrete: compliance failures, audit gaps, data incidents, engineer-hours lost
- One sharp statistic or scenario per pain point — sourced from BART_VALIDATED_OUTPUT only

Authority + social proof (Trust Strip, Technical Credibility, Social Proof):
- Trust strip: named enterprises only — no "leading companies" generics
- Technical Credibility: codebase-validated facts from Bart only; format as evidence, not claims
- Social proof: name/title/company for every testimonial; specific outcomes over adjectives

Reciprocity (Hero, Offer):
- If an offer exists, lead with it — give before asking
- Frame the CTA as access to value, not a transaction ("See it live" not "Submit")

Commitment escalation (FAQ):
- FAQ is the objection-handling close — address the real reasons people don't convert
- End each answer with a forward-lean: what they gain by acting, not just reassurance

SCROLL MECHANICS — every section must pull the reader to the next:

Hero:
- H1: outcome-first, primary keyword verbatim, ≤80 chars, Title Case
- Subheadline: one sentence that names the specific pain and the specific relief
- 3 outcome bullets: lead with the result, explain the mechanism in 6 words or fewer
- CTA button copy: benefit-led ("See DataHub govern your data"), not action-led ("Submit")

H2 cadence:
- 30–50% of H2s as open-loop questions that the section answers ("What does governance failure actually cost?")
- Remaining H2s: outcome statements, not feature labels ("End-to-end lineage in under 10 minutes")
- No H2 should be skippable — each must create a reason to keep reading

Paragraph + bullet discipline:
- Maximum 3 lines per paragraph — hard limit
- Follow every 2–3 sentence block with a bullet list or visual anchor
- No wall-of-text sections anywhere on the page

Section transitions:
- Each section's final sentence should tease what comes next or raise a question the next section answers
- Never end a section with a summary — end with a lean forward

FAQ placement and structure:
- 4–6 questions, each one a real sales objection ("Does DataHub work with our existing stack?")
- Keep answers to 3–5 sentences: validate the concern, resolve it, restate the benefit
- Place FAQ immediately before final CTA to clear the last objections before the ask

Final CTA section:
- Restate the single biggest outcome from the hero
- Add one risk-reduction line near the form ("No credit card. 20-minute session.")
- CTA button copy must differ slightly from hero CTA — reinforce momentum, not repetition

━━━ SEO RULES ━━━
- Page word count: 900–1,500 words
- Primary keyword verbatim in: title tag (≤60 chars), H1 (≤80 chars), first 100 words, meta description (≤140 chars), and at least one H2
- Each secondary keyword in at least one H2/H3/H4
- Sentence case for all headings except H1
- No exclamation marks. Active voice. No weasel words — quantify or omit

━━━ OUTPUT FORMAT ━━━
Return ONLY valid JSON — no code fences, no preamble. All string values must be properly escaped (double quotes inside strings use \", newlines use \n). Return ONLY valid JSON with exactly these keys:
{{
  "seo_json": {{
    "title_tag": "",
    "meta_description": "",
    "slug": "",
    "h1": "",
    "hubspot_form_id": "{form_id}",
    "intent_type": "",
    "cta_type": ""
  }},
  "outline_md": "",
  "copy_md": "",
  "cta_microcopy": {{
    "hero_button": "",
    "hero_risk_reduction": "",
    "final_button": "",
    "final_risk_reduction": ""
  }},
  "image_briefs_md": "",
  "qa_checklist_md": ""
}}""".strip()

def build_lp_html_prompt(
    fields: dict,
    writer_json: dict,
    svgs: Dict[str, str],
    secondary_keywords: List[str],
) -> str:
    secondary_block = (
        "\n".join(f"- {k}" for k in secondary_keywords) if secondary_keywords else "(none)"
    )
    picture_elements = ""
    for svg_name in svgs:
        picture_elements += (
            f'\n<picture>\n'
            f'  <source srcset="images/{svg_name}" type="image/svg+xml">\n'
            f'  <img src="images/{svg_name}" alt="[descriptive alt text]" loading="lazy">\n'
            f'</picture>'
        )
    form_id = writer_json.get("seo_json", {}).get(
        "hubspot_form_id", _hubspot_form_id(fields.get("primary_cta", "Demo"))
    )
    return f"""You are the HTML Builder. This is the final build step.

HARD CONSTRAINTS — follow these documents exactly:

[DATAHUB BRAND SYSTEM]
{BRAND_SKILL_MD}

[SAMPLE LANDING PAGE TEMPLATE — replicate this structure and style]
{SAMPLE_LP_HTML}

Inputs:
- primary keyword: "{fields["search_term"]}"
- secondary keywords:
{secondary_block}

Content to use exactly (no new claims, no invented product assertions):

SEO_JSON:
{json.dumps(writer_json.get("seo_json", {}), indent=2)}

OUTLINE_MD:
{writer_json.get("outline_md", "")}

COPY_MD:
{writer_json.get("copy_md", "")}

CTA_MICROCOPY — use these exact strings for buttons and risk-reduction lines:
{json.dumps(writer_json.get("cta_microcopy", {}), indent=2)}

IMAGE_BRIEFS_MD:
{writer_json.get("image_briefs_md", "")}

Available diagram images — use these exact <picture> elements verbatim, do NOT write bare <img> tags or reference .png files for diagrams:
{picture_elements if picture_elements else "(none)"}

Non-negotiable output rules:
- Output ONLY the contents of <body>…</body> — nothing else
- Do NOT write <!doctype>, <html>, <head>, <title>, <meta>, <style>, or <link> tags
- Do NOT write any CSS — the stylesheet is already handled
- Start your output with the first element inside <body> (e.g. the scroll progress bar or header)
- End your output with the last element before </body> (e.g. the footer or script tags)
- Title tag and meta description are handled separately — do not include them
- H1 must include primary keyword verbatim: "{fields["search_term"]}"
- Header: background #F2F1EE, border-bottom 1px solid #DDDBD6
  Logo: <img src="images/dataHub_logo_color_black.svg" alt="DataHub"> — no text logo
- Hero: background #F2F1EE — never dark; all hero text in dark neutrals
- No italic text anywhere — font-style: normal throughout; no <em> or <i> tags
- Visual section: grid-template-columns: 1fr (stacked vertically, never side by side)
- HubSpot form embedded in hero AND final CTA section
  portalId: '14552909', formId: '{form_id}', region: 'na1'
- No global navigation — header contains only logo + one CTA button
- Full DataHub footer: 4 nav columns, social links (LinkedIn/GitHub/Twitter/Slack), legal bar
  matching the sample template footer exactly — copy the footer structure from the sample template verbatim
- CSS variables only (--dh-*), Google Fonts Castoro + Geist — no system fonts, no Arial/Inter
- No invented metrics, logos, or social proof
- Section spacing and layout: follow the sample template exactly — use the same padding, gap, and grid values as the template; do not invent new spacing
- Card grid headlines (How It Works steps, benefit blocks, feature tiles): keep all headlines in a grid to 4–6 words — consistent length across every card in the same section so they align at the same height
- TRUST STRIP: Do NOT write the logo scroller / trust strip section. Instead output exactly this placeholder on its own line, immediately after the closing </section> tag of the hero:
  <!-- TRUST_STRIP_PLACEHOLDER -->
  The trust strip will be injected automatically in code.

Return ONLY the HTML — no code fences, no preamble, no explanation.
""".strip()

def _request_id(thread_ts: str) -> str:
    """Derive a short, human-readable request ID from a Slack thread_ts.
    e.g. '1741234567.123456' → '20260311-4567'
    """
    try:
        ts_int = int(float(thread_ts))
        date_str = datetime.utcfromtimestamp(ts_int).strftime("%Y%m%d")
        short = str(ts_int)[-4:]
        return f"{date_str}-{short}"
    except Exception:
        return ""

async def generate_full_lp(
    fields: dict,
    bart_brief: str,
    svgs: Dict[str, str],
    secondary_keywords: List[str],
    request_id: str = "",
) -> Dict[str, str]:
    writer_prompt = build_copywriter_prompt(fields, bart_brief, secondary_keywords)
    writer_raw = await claude_text(writer_prompt, max_tokens=8000)

    # Strip code fences if Claude wrapped the JSON
    writer_raw = re.sub(r'^```(?:json)?\s*', '', writer_raw.strip(), flags=re.IGNORECASE)
    writer_raw = re.sub(r'\s*```$', '', writer_raw.strip())

    try:
        writer_json = json.loads(writer_raw)
    except Exception:
        # Try extracting just the outermost JSON object
        match = re.search(r'\{[\s\S]*\}', writer_raw)
        if match:
            try:
                writer_json = json.loads(match.group(0))
            except Exception:
                # Last resort: ask Claude to fix it
                fix_prompt = (
                    "The following text is meant to be valid JSON but has a syntax error. "
                    "Fix it and return ONLY the corrected JSON with no explanation:\n\n"
                    + match.group(0)[:6000]
                )
                fixed = await claude_text(fix_prompt, max_tokens=8000)
                fixed = re.sub(r'^```(?:json)?\s*', '', fixed.strip(), flags=re.IGNORECASE)
                fixed = re.sub(r'\s*```$', '', fixed.strip())
                writer_json = json.loads(fixed)
        else:
            raise ValueError(f"Writer did not return valid JSON: {writer_raw[:500]}")

    html_prompt = build_lp_html_prompt(fields, writer_json, svgs, secondary_keywords)
    page_html = await claude_text(html_prompt, max_tokens=8000)

    # Claude returns body content only — strip any accidental wrapper tags
    page_html = re.sub(r'(?i)<!doctype[^>]*>', '', page_html).strip()
    page_html = re.sub(r'(?i)</?html[^>]*>', '', page_html).strip()
    # Strip <head>...</head> if Claude included one despite instructions
    page_html = re.sub(r'(?i)<head[\s\S]*?</head>', '', page_html).strip()
    # Strip accidental <body> / </body> wrapper tags
    page_html = re.sub(r'(?i)<body[^>]*>', '', page_html).strip()
    page_html = re.sub(r'(?i)</body>', '', page_html).strip()

    # Inject hardcoded trust strip — replace placeholder if present, otherwise insert after first </section>
    if '<!-- TRUST_STRIP_PLACEHOLDER -->' in page_html:
        page_html = page_html.replace('<!-- TRUST_STRIP_PLACEHOLDER -->', TRUST_STRIP_HTML)
    else:
        # Fallback: insert after the first closing </section> (end of hero)
        page_html = page_html.replace('</section>', f'</section>\n{TRUST_STRIP_HTML}', 1)

    # Guarantee footer — if Claude hit the token limit, append the template footer verbatim
    if '<footer' not in page_html.lower() and TEMPLATE_FOOTER_HTML:
        page_html = page_html + '\n' + TEMPLATE_FOOTER_HTML

    # Assemble metadata and full page
    seo = writer_json.get("seo_json", {})
    raw_slug = (seo.get("slug") or slugify(fields["search_term"])).strip("/")
    if request_id:
        raw_slug = f"{raw_slug}-{request_id}"
    metadata = {
        "slug": raw_slug or slugify(fields["search_term"]),
        "primary_search_term": fields["search_term"],
        "intent_type": seo.get("intent_type") or fields.get("intent", ""),
        "cta_type": seo.get("cta_type") or fields.get("primary_cta", ""),
        "hubspot_form_id": seo.get("hubspot_form_id") or _hubspot_form_id(fields.get("primary_cta", "Demo")),
        "title_tag": seo.get("title_tag") or "",
        "meta_description": seo.get("meta_description") or "",
        "h1": seo.get("h1") or "",
        "generated_date": datetime.now().strftime("%Y-%m-%d"),
        "bart_done": True,
    }

    # Wrap body content with the template head (CSS included, no token waste)
    head = build_page_head(metadata["title_tag"], metadata["meta_description"])
    full_html = f"<!doctype html>\n<html lang=\"en\">\n{head}\n<body>\n{page_html}\n</body>\n</html>"

    pages_url = (
        f"{GITHUB_PAGES_BASE}/generated-pages/{metadata['slug']}/"
        if GITHUB_PAGES_BASE else ""
    )
    return {
        "html": full_html,
        "metadata_json": json.dumps(metadata, indent=2),
        "writer_json": writer_json,
        "slug": metadata["slug"],
        "pages_url": pages_url,
    }

# ----------------------------
# GitHub commit helpers
# ----------------------------
async def github_commit_file(
    repo: str, path: str, content: str, message: str, branch: str
) -> bool:
    if not GITHUB_TOKEN or not repo:
        logger.warning("GitHub commit skipped — GITHUB_TOKEN or GITHUB_REPO not set")
        return False

    encoded = base64.b64encode(content.encode("utf-8")).decode("utf-8")
    url = f"https://api.github.com/repos/{repo}/contents/{path}"
    headers = {
        "Authorization": f"token {GITHUB_TOKEN}",
        "Accept": "application/vnd.github.v3+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }

    async with httpx.AsyncClient(timeout=30) as client:
        r = await client.get(url, headers=headers, params={"ref": branch})
        sha = r.json().get("sha") if r.status_code == 200 else None

        payload: Dict[str, Any] = {"message": message, "content": encoded, "branch": branch}
        if sha:
            payload["sha"] = sha

        resp = await client.put(url, headers=headers, json=payload)
        if resp.status_code not in (200, 201):
            logger.error("GitHub commit failed for %s: %s %s", path, resp.status_code, resp.text[:300])
            return False
        return True

async def github_commit_files(
    repo: str,
    files: Dict[str, str],
    commit_message: str,
    branch: str,
) -> Tuple[bool, List[str]]:
    failed: List[str] = []
    for path, content in files.items():
        ok = await github_commit_file(repo, path, content, commit_message, branch)
        if not ok:
            failed.append(path)
    return (len(failed) == 0, failed)

# ----------------------------
# Modal helpers
# ----------------------------
def build_modal_view(initial_search_term: str = "", channel_id: str = "") -> Dict[str, Any]:
    return {
        "type": "modal",
        "callback_id": "lp_request_modal",
        "private_metadata": channel_id or "",
        "title": {"type": "plain_text", "text": "SEM LP Request"},
        "submit": {"type": "plain_text", "text": "Create"},
        "close": {"type": "plain_text", "text": "Cancel"},
        "blocks": [
            {
                "type": "input",
                "block_id": "search_term_block",
                "label": {"type": "plain_text", "text": "Search term (exact)"},
                "element": {
                    "type": "plain_text_input",
                    "action_id": "search_term",
                    "initial_value": initial_search_term or "",
                    "placeholder": {"type": "plain_text", "text": "e.g., datahub lineage"},
                },
            },
            {
                "type": "input",
                "optional": True,
                "block_id": "secondary_keywords_block",
                "label": {"type": "plain_text", "text": "Secondary keywords (optional)"},
                "element": {
                    "type": "plain_text_input",
                    "action_id": "secondary_keywords",
                    "multiline": True,
                    "placeholder": {
                        "type": "plain_text",
                        "text": "One per line (or comma-separated)\nExample:\nmetadata management\ncolumn-level lineage\ndata observability",
                    },
                },
            },
            {
                "type": "input",
                "block_id": "primary_cta_block",
                "label": {"type": "plain_text", "text": "Primary CTA"},
                "element": {
                    "type": "static_select",
                    "action_id": "primary_cta",
                    "options": [
                        {"text": {"type": "plain_text", "text": "Demo"}, "value": "Demo"},
                        {"text": {"type": "plain_text", "text": "Free Trial"}, "value": "Free Trial"},
                        {"text": {"type": "plain_text", "text": "Product Tour"}, "value": "Product Tour"},
                        {"text": {"type": "plain_text", "text": "Bi-weekly Demo"}, "value": "Bi-weekly Demo"},
                    ],
                },
            },
            {
                "type": "input",
                "block_id": "intent_block",
                "label": {"type": "plain_text", "text": "Intent (required)"},
                "element": {
                    "type": "static_select",
                    "action_id": "intent",
                    "options": [
                        {"text": {"type": "plain_text", "text": "Commercial"}, "value": "Commercial"},
                        {"text": {"type": "plain_text", "text": "Educational"}, "value": "Educational"},
                        {"text": {"type": "plain_text", "text": "Transactional"}, "value": "Transactional"},
                    ],
                },
            },
            {
                "type": "input",
                "block_id": "primary_audience_block",
                "label": {"type": "plain_text", "text": "Primary Audience (required)"},
                "element": {
                    "type": "static_select",
                    "action_id": "primary_audience",
                    "options": [
                        {"text": {"type": "plain_text", "text": "Economic Buyer"}, "value": "Economic Buyer"},
                        {"text": {"type": "plain_text", "text": "Platform Engineer"}, "value": "Platform Engineer"},
                    ],
                },
            },
            {
                "type": "input",
                "optional": True,
                "block_id": "offer_block",
                "label": {"type": "plain_text", "text": "Offer (optional)"},
                "element": {"type": "plain_text_input", "action_id": "offer", "multiline": True},
            },
            {
                "type": "input",
                "optional": True,
                "block_id": "must_include_block",
                "label": {"type": "plain_text", "text": "Must include (optional)"},
                "element": {"type": "plain_text_input", "action_id": "must_include", "multiline": True},
            },
            {
                "type": "input",
                "optional": True,
                "block_id": "must_not_say_block",
                "label": {"type": "plain_text", "text": "Must not say (optional)"},
                "element": {"type": "plain_text_input", "action_id": "must_not_say", "multiline": True},
            },
        ],
    }

def extract_modal_values(view_state: Dict[str, Any]) -> Dict[str, Any]:
    values = view_state.get("values", {})

    def get_value(block_id: str, action_id: str) -> Optional[str]:
        block = values.get(block_id, {})
        action = block.get(action_id, {})
        if "value" in action:
            return action.get("value")
        selected = action.get("selected_option")
        if selected:
            return selected.get("value")
        return None

    return {
        "search_term": get_value("search_term_block", "search_term"),
        "secondary_keywords": get_value("secondary_keywords_block", "secondary_keywords"),
        "primary_cta": get_value("primary_cta_block", "primary_cta"),
        "intent": get_value("intent_block", "intent"),
        "primary_audience": get_value("primary_audience_block", "primary_audience"),
        "offer": get_value("offer_block", "offer"),
        "must_include": get_value("must_include_block", "must_include"),
        "must_not_say": get_value("must_not_say_block", "must_not_say"),
    }

# ----------------------------
# Bart prompt
# ----------------------------
def bart_prompt(search_term: str, primary_cta: str, intent: str, secondary_keywords: List[str]) -> str:
    secondary = "\n".join(f"- {k}" for k in secondary_keywords) if secondary_keywords else "(none)"
    return f"""<@{BART_USER_ID}> You are validating + drafting a technically accurate SEM landing page outline.

Context:
- Audience: Platform Engineer
- Search term (exact): "{search_term}"
- Secondary keywords (optional):
{secondary}
- Primary CTA: {primary_cta}
- Intent: {intent}

TASK A — Codebase validation (required):
Validate any capabilities/claims you mention by checking the codebase.
For each claim include: ✅/⚠️/❌ + evidence (file paths/settings).

TASK B — Landing page outline (required):
Angle (2 sentences), H1 w/ exact search term, H2/H3/H4 outline + bullets, 3–6 FAQs.

TASK C — Image generation (required):
Generate 1–2 visuals (diagram preferred). Upload images to this thread with captions + alt text.

When you're fully done (claims validated + images uploaded), reply with exactly: BART_DONE
"""

# ----------------------------
# Claude helpers
# ----------------------------
def claude_text_sync(prompt: str, max_tokens: int = 3500) -> str:
    if not anthropic_client:
        raise RuntimeError("Missing ANTHROPIC_API_KEY")
    msg = anthropic_client.messages.create(
        model=CLAUDE_MODEL,
        max_tokens=max_tokens,
        temperature=0.2,
        messages=[{"role": "user", "content": prompt}],
    )
    parts = []
    for block in msg.content:
        if getattr(block, "type", None) == "text":
            parts.append(block.text)
    return "\n".join(parts).strip()

async def claude_text(prompt: str, max_tokens: int = 3500) -> str:
    return await asyncio.to_thread(claude_text_sync, prompt, max_tokens)

# ----------------------------
# Thread link parsing (for manual build trigger)
# ----------------------------
def parse_slack_thread_link(link: str) -> Tuple[Optional[str], Optional[str]]:
    """
    Extract (channel_id, thread_ts) from a Slack thread link.
    Handles both root message links and reply links (which carry thread_ts as a query param).
    """
    # Extract channel ID
    channel_match = re.search(r'/archives/([A-Z0-9]+)', link)
    if not channel_match:
        return None, None
    channel_id = channel_match.group(1)

    # Prefer thread_ts query param (present when link is copied from a reply)
    qs_match = re.search(r'thread_ts=(\d+\.\d+)', link)
    if qs_match:
        return channel_id, qs_match.group(1)

    # Fall back to the p... path segment (root message link)
    p_match = re.search(r'/p(\d{16})', link)
    if p_match:
        raw_ts = p_match.group(1)
        thread_ts = raw_ts[:-6] + "." + raw_ts[-6:]
        return channel_id, thread_ts

    return None, None

def build_build_modal_view(channel_id: str = "") -> Dict[str, Any]:
    """Modal for /sem-lp-build — manual pipeline trigger."""
    return {
        "type": "modal",
        "callback_id": "lp_build_modal",
        "private_metadata": channel_id or "",
        "title": {"type": "plain_text", "text": "Manual LP Build"},
        "submit": {"type": "plain_text", "text": "Build"},
        "close": {"type": "plain_text", "text": "Cancel"},
        "blocks": [
            {
                "type": "input",
                "block_id": "thread_link_block",
                "label": {"type": "plain_text", "text": "Bart thread link"},
                "hint": {"type": "plain_text", "text": "Go to #sem-lp-requests, right-click any message in the Bart thread → Copy link"},
                "element": {
                    "type": "plain_text_input",
                    "action_id": "thread_link",
                    "placeholder": {"type": "plain_text", "text": "https://yourworkspace.slack.com/archives/G.../p..."},
                },
            },
            {
                "type": "input",
                "block_id": "search_term_block",
                "label": {"type": "plain_text", "text": "Search term (exact)"},
                "element": {
                    "type": "plain_text_input",
                    "action_id": "search_term",
                    "placeholder": {"type": "plain_text", "text": "e.g., data governance software"},
                },
            },
            {
                "type": "input",
                "optional": True,
                "block_id": "secondary_keywords_block",
                "label": {"type": "plain_text", "text": "Secondary keywords (optional)"},
                "element": {
                    "type": "plain_text_input",
                    "action_id": "secondary_keywords",
                    "multiline": True,
                    "placeholder": {"type": "plain_text", "text": "One per line or comma-separated"},
                },
            },
            {
                "type": "input",
                "block_id": "primary_cta_block",
                "label": {"type": "plain_text", "text": "Primary CTA"},
                "element": {
                    "type": "static_select",
                    "action_id": "primary_cta",
                    "options": [
                        {"text": {"type": "plain_text", "text": "Demo"}, "value": "Demo"},
                        {"text": {"type": "plain_text", "text": "Free Trial"}, "value": "Free Trial"},
                        {"text": {"type": "plain_text", "text": "Product Tour"}, "value": "Product Tour"},
                        {"text": {"type": "plain_text", "text": "Bi-weekly Demo"}, "value": "Bi-weekly Demo"},
                    ],
                },
            },
            {
                "type": "input",
                "block_id": "intent_block",
                "label": {"type": "plain_text", "text": "Intent"},
                "element": {
                    "type": "static_select",
                    "action_id": "intent",
                    "options": [
                        {"text": {"type": "plain_text", "text": "Commercial"}, "value": "Commercial"},
                        {"text": {"type": "plain_text", "text": "Educational"}, "value": "Educational"},
                        {"text": {"type": "plain_text", "text": "Transactional"}, "value": "Transactional"},
                    ],
                },
            },
            {
                "type": "input",
                "block_id": "primary_audience_block",
                "label": {"type": "plain_text", "text": "Primary Audience"},
                "element": {
                    "type": "static_select",
                    "action_id": "primary_audience",
                    "options": [
                        {"text": {"type": "plain_text", "text": "Economic Buyer"}, "value": "Economic Buyer"},
                        {"text": {"type": "plain_text", "text": "Platform Engineer"}, "value": "Platform Engineer"},
                    ],
                },
            },
            {
                "type": "input",
                "optional": True,
                "block_id": "must_include_block",
                "label": {"type": "plain_text", "text": "Must include (optional)"},
                "element": {"type": "plain_text_input", "action_id": "must_include", "multiline": True},
            },
        ],
    }

# ----------------------------
# Routes
# ----------------------------
@app.get("/health")
async def health():
    return {"ok": True}

@app.get("/debug/jobs")
async def debug_jobs():
    return {"count": len(JOBS), "jobs": {k: {**v, "fields": "(omitted)"} for k, v in JOBS.items()}}

@app.get("/anthropic/models")
async def anthropic_models():
    if not ANTHROPIC_API_KEY:
        return {"ok": False, "error": "Missing ANTHROPIC_API_KEY"}
    headers = {
        "x-api-key": ANTHROPIC_API_KEY,
        "anthropic-version": "2023-06-01",
    }
    async with httpx.AsyncClient(timeout=20) as client:
        r = await client.get("https://api.anthropic.com/v1/models", headers=headers)
        return {"status_code": r.status_code, "json": r.json()}

@app.post("/slack/commands")
async def slack_commands(request: Request):
    raw_body = await request.body()
    verify_slack_signature(
        raw_body,
        request.headers.get("X-Slack-Request-Timestamp", ""),
        request.headers.get("X-Slack-Signature", ""),
    )
    form = await request.form()
    command = form.get("command")
    trigger_id = form.get("trigger_id")
    text = (form.get("text") or "").strip()
    channel_id = form.get("channel_id") or ""

    if command == "/sem-lp-request":
        view = build_modal_view(initial_search_term=text, channel_id=channel_id)
        await slack_api("views.open", {"trigger_id": trigger_id, "view": view})
        return PlainTextResponse("", status_code=200)

    if command == "/sem-lp-build":
        view = build_build_modal_view(channel_id=channel_id)
        await slack_api("views.open", {"trigger_id": trigger_id, "view": view})
        return PlainTextResponse("", status_code=200)

    return PlainTextResponse("Unsupported command.", status_code=200)

@app.post("/slack/interactions")
async def slack_interactions(request: Request):
    return await _handle_interactivity(request)

@app.post("/slack/interactivity")
async def slack_interactivity(request: Request):
    return await _handle_interactivity(request)

async def _handle_build_modal(payload: dict, view: dict) -> JSONResponse:
    """Handle /sem-lp-build modal submission — manual pipeline trigger from a Bart thread."""
    values = view.get("state", {}).get("values", {})

    def gv(block_id: str, action_id: str) -> Optional[str]:
        block = values.get(block_id, {})
        action = block.get(action_id, {})
        if "value" in action:
            return action.get("value")
        sel = action.get("selected_option")
        return sel.get("value") if sel else None

    thread_link = (gv("thread_link_block", "thread_link") or "").strip()
    search_term = (gv("search_term_block", "search_term") or "").strip()
    primary_cta = gv("primary_cta_block", "primary_cta") or "Demo"
    intent = gv("intent_block", "intent") or "Commercial"
    primary_audience = gv("primary_audience_block", "primary_audience") or ""
    secondary_keywords = parse_secondary_keywords(gv("secondary_keywords_block", "secondary_keywords"))
    must_include = gv("must_include_block", "must_include") or ""

    errors: Dict[str, str] = {}
    if not thread_link:
        errors["thread_link_block"] = "Paste the Slack link to the Bart thread."
    if not search_term:
        errors["search_term_block"] = "Search term is required."

    _parsed_channel, thread_ts = parse_slack_thread_link(thread_link)
    if thread_link and not thread_ts:
        errors["thread_link_block"] = "Couldn't parse that link — right-click the thread message and choose Copy link."
    # Always fetch from the private Bart channel regardless of what's in the link
    bart_channel = SEM_LP_REQUESTS_CHANNEL or _parsed_channel

    if errors:
        return JSONResponse({"response_action": "errors", "errors": errors})

    user_id = (payload.get("user") or {}).get("id") or "unknown"
    requester_channel = (view.get("private_metadata") or "").strip() or SEM_LP_BUILD_KITS_CHANNEL or SLACK_DEFAULT_CHANNEL
    request_id = generate_request_id()
    slug = slugify(search_term)

    fields = {
        "search_term": search_term,
        "primary_cta": primary_cta,
        "intent": intent,
        "primary_audience": primary_audience,
        "secondary_keywords": None,
        "must_include": must_include,
        "offer": "",
        "must_not_say": "",
    }

    async def run_manual_build():
        try:
            await post_message(
                requester_channel,
                f"🔧 Manual build started — `{search_term}` _(Request ID: {request_id})_\n"
                f"Fetching Bart's thread and building now…",
            )

            # Fetch and accumulate full Bart brief from the thread
            messages = await fetch_thread_messages(bart_channel, thread_ts)
            logger.info("MANUAL BUILD thread_ts=%s channel=%s messages_found=%s user_ids=%s",
                        thread_ts, bart_channel, len(messages),
                        [m.get("user") for m in messages])

            bart_brief = accumulate_bart_brief(messages, BART_USER_ID)

            # Fallback: if BART_USER_ID doesn't match, use all non-bot messages in the thread
            if not bart_brief:
                logger.warning("No Bart messages found by user ID — falling back to all thread messages")
                parts = [
                    (m.get("text") or "").strip()
                    for m in messages
                    if (m.get("text") or "").strip() and not m.get("bot_id")
                ]
                bart_brief = "\n\n---\n\n".join(parts)

            if not bart_brief:
                await post_message(
                    requester_channel,
                    f"⚠️ No messages found in that thread. Double-check the link and try again."
                )
                return

            # Generate SVGs
            image_refs = parse_image_refs(bart_brief)
            svgs: Dict[str, str] = {}
            if image_refs:
                await post_message(
                    requester_channel,
                    f"🎨 Generating {len(image_refs)} SVG(s)…",
                )
                svgs = await generate_svgs(bart_brief, slug)

            # Generate LP package
            await post_message(requester_channel, "✍️ Conversion copywriting + HTML build…")
            lp_package = await generate_full_lp(fields, bart_brief, svgs, secondary_keywords, request_id=_request_id(thread_ts))
            final_slug = lp_package["slug"]

            # Commit to GitHub
            files_to_commit: Dict[str, str] = {
                f"generated-pages/{final_slug}/index.html": lp_package["html"],
                f"generated-pages/{final_slug}/metadata.json": lp_package["metadata_json"],
                f"generated-pages/{final_slug}/brief.md": bart_brief,
            }
            for svg_name, svg_content in svgs.items():
                files_to_commit[f"generated-pages/{final_slug}/images/{svg_name}"] = svg_content
            if LOGO_SVG_BLACK and not LOGO_SVG_BLACK.startswith("[Missing"):
                files_to_commit[f"generated-pages/{final_slug}/images/dataHub_logo_color_black.svg"] = LOGO_SVG_BLACK

            kit_url = (
                f"https://github.com/{GITHUB_REPO}/tree/{GITHUB_BRANCH}"
                f"/generated-pages/{final_slug}"
            )

            if GITHUB_TOKEN and GITHUB_REPO:
                await post_message(requester_channel, "📤 Committing to GitHub…")
                all_ok, failed_paths = await github_commit_files(
                    GITHUB_REPO, files_to_commit,
                    f"Add LP package: {final_slug}", GITHUB_BRANCH,
                )
                if all_ok:
                    preview = lp_package.get("pages_url", "")
                    result_msg = (
                        f"✅ *LP package ready*\n"
                        f"*Search term:* {search_term}\n"
                        f"*Slug:* `{final_slug}`\n"
                        f"*Files:* {kit_url}"
                        + (f"\n*Preview:* {preview}" if preview else "")
                    )
                else:
                    result_msg = (
                        f"⚠️ *LP generated* — `{final_slug}` — some files failed:\n"
                        + "\n".join(f"• `{p}`" for p in failed_paths)
                    )
            else:
                result_msg = f"✅ *LP package generated* — `{final_slug}` (GitHub not configured)"

            await post_message(requester_channel, result_msg)

        except Exception as e:
            logger.exception("Manual build failed: %s", e)
            try:
                await post_message(requester_channel, f"❌ Manual build failed: `{e}`")
            except Exception:
                pass

    asyncio.create_task(run_manual_build())
    return JSONResponse({"response_action": "clear"})


async def _handle_interactivity(request: Request):
    raw_body = await request.body()
    logger.info("INTERACTIVITY hit bytes=%s path=%s", len(raw_body), request.url.path)

    try:
        verify_slack_signature(
            raw_body,
            request.headers.get("X-Slack-Request-Timestamp", ""),
            request.headers.get("X-Slack-Signature", ""),
        )

        form = await request.form()
        payload_raw = form.get("payload")
        if not payload_raw:
            return JSONResponse({"ok": True})

        payload = json.loads(payload_raw)
        if payload.get("type") != "view_submission":
            return JSONResponse({"ok": True})

        view = payload.get("view", {})
        callback_id = view.get("callback_id")

        if callback_id == "lp_build_modal":
            return await _handle_build_modal(payload, view)

        if callback_id != "lp_request_modal":
            return JSONResponse({"response_action": "clear"})

        fields = extract_modal_values(view.get("state", {}))

        errors = {}
        if not fields.get("search_term"):
            errors["search_term_block"] = "Search term is required."
        if not fields.get("primary_cta"):
            errors["primary_cta_block"] = "Primary CTA is required."
        if not fields.get("intent"):
            errors["intent_block"] = "Intent is required."
        if not fields.get("primary_audience"):
            errors["primary_audience_block"] = "Primary Audience is required."
        if errors:
            return JSONResponse({"response_action": "errors", "errors": errors})

        request_id = generate_request_id()
        slug = slugify(fields["search_term"])
        user_id = (payload.get("user") or {}).get("id") or "unknown"

        # Channel where the slash command was run (agency-facing, e.g. #sem-lp-build-kits)
        requester_channel = (view.get("private_metadata") or "").strip() or SLACK_DEFAULT_CHANNEL or ""
        if not requester_channel:
            return JSONResponse({"response_action": "clear"})

        # Private Bart channel — fall back to requester_channel if not configured
        bart_channel = SEM_LP_REQUESTS_CHANNEL or requester_channel

        secondary_keywords = parse_secondary_keywords(fields.get("secondary_keywords"))

        async def run_pipeline():
            try:
                # Acknowledge in the agency channel immediately
                await post_message(
                    requester_channel,
                    f"Got it — drafting `{fields['search_term']}` now. "
                    f"I'll post the package here when it's ready. _(Request ID: {request_id})_",
                )

                # Start the Bart thread in the private channel
                starter = (
                    f"🚀 *LP request started*\n"
                    f"*Request ID:* {request_id}\n"
                    f"*Search term:* {fields['search_term']}\n"
                    f"*Secondary keywords:* {', '.join(secondary_keywords) if secondary_keywords else '—'}\n"
                    f"*Primary CTA:* {fields['primary_cta']}\n"
                    f"*Intent:* {fields['intent']}\n"
                    f"*Primary Audience:* {fields['primary_audience']}\n"
                    f"*Requester:* <@{user_id}>"
                )
                bart_thread_ts = await post_message(bart_channel, starter)

                JOBS[bart_thread_ts] = {
                    "request_id": request_id,
                    "slug": slug,
                    "bart_channel": bart_channel,
                    "requester_channel": requester_channel,
                    "user_id": user_id,
                    "fields": fields,
                    "secondary_keywords": secondary_keywords,
                    "awaiting": "bart",
                    "bart_output": None,
                }
                _save_jobs()

                await post_message(
                    bart_channel,
                    bart_prompt(fields["search_term"], fields["primary_cta"], fields["intent"], secondary_keywords),
                    thread_ts=bart_thread_ts,
                )
                await post_message(
                    bart_channel,
                    "⏳ Waiting for Bart… pipeline continues automatically after `BART_DONE`.",
                    thread_ts=bart_thread_ts,
                )

            except Exception as e:
                logger.exception("run_pipeline failed: %s", e)
                try:
                    await post_message(requester_channel, f"❌ Pipeline failed to start: `{e}`")
                except Exception:
                    pass

        asyncio.create_task(run_pipeline())
        return JSONResponse({"response_action": "clear"})

    except Exception as e:
        logger.exception("Interactivity handler error: %s", e)
        return JSONResponse({"response_action": "clear"})

@app.post("/slack/events")
async def slack_events(request: Request):
    raw_body = await request.body()
    verify_slack_signature(
        raw_body,
        request.headers.get("X-Slack-Request-Timestamp", ""),
        request.headers.get("X-Slack-Signature", ""),
    )
    body = json.loads(raw_body.decode("utf-8") or "{}")

    if body.get("type") == "url_verification":
        return JSONResponse({"challenge": body.get("challenge")})

    event = body.get("event", {}) or {}
    if event.get("type") != "message":
        return JSONResponse({"ok": True})
    if event.get("subtype"):
        return JSONResponse({"ok": True})

    thread_ts = event.get("thread_ts") or event.get("ts")
    user_id = event.get("user") or ""
    text = (event.get("text") or "").strip()

    logger.info("EVENT user=%s thread_ts=%s jobs_loaded=%s bart_done=%s text_preview=%s",
                user_id, thread_ts, list(JOBS.keys()), "BART_DONE" in text, text[:80])

    job = JOBS.get(thread_ts)

    # If job not in memory (e.g. Render restarted) but Bart posted BART_DONE,
    # reconstruct the job from the thread's starter message
    if not job and user_id == BART_USER_ID and "BART_DONE" in text and thread_ts:
        logger.info("Job not in memory — attempting reconstruction from thread %s", thread_ts)
        try:
            bart_channel = SEM_LP_REQUESTS_CHANNEL or SLACK_DEFAULT_CHANNEL
            thread_messages = await fetch_thread_messages(bart_channel, thread_ts)
            starter = next(
                (m for m in thread_messages if "Search term:" in (m.get("text") or "")),
                None
            )
            if starter:
                starter_text = starter.get("text", "")
                def _parse_field(label: str) -> str:
                    m = re.search(rf'\*{label}:\*\s*(.+)', starter_text)
                    return m.group(1).strip() if m else ""
                search_term = _parse_field("Search term")
                job = {
                    "request_id": _parse_field("Request ID") or generate_request_id(),
                    "slug": slugify(search_term),
                    "bart_channel": bart_channel,
                    "requester_channel": SEM_LP_BUILD_KITS_CHANNEL or SLACK_DEFAULT_CHANNEL,
                    "fields": {
                        "search_term": search_term,
                        "primary_cta": _parse_field("Primary CTA") or "Demo",
                        "intent": _parse_field("Intent") or "Commercial",
                        "primary_audience": _parse_field("Primary Audience") or "",
                        "secondary_keywords": None,
                        "offer": "", "must_include": "", "must_not_say": "",
                    },
                    "secondary_keywords": [],
                    "awaiting": "bart",
                }
                JOBS[thread_ts] = job
                _save_jobs()
                logger.info("Job reconstructed for thread %s search_term=%s", thread_ts, search_term)
        except Exception as e:
            logger.warning("Job reconstruction failed: %s", e)

    if not job:
        return JSONResponse({"ok": True})

    if job.get("awaiting") == "bart" and user_id == BART_USER_ID and "BART_DONE" in text:
        job["bart_output"] = text
        job["awaiting"] = "generating"
        JOBS[thread_ts] = job
        _save_jobs()

        bart_channel = job["bart_channel"]
        requester_channel = job["requester_channel"]
        request_id = job["request_id"]
        fields = job["fields"]
        slug = job["slug"]
        secondary_keywords = job.get("secondary_keywords", [])

        async def continue_pipeline():
            try:
                # Step 1 — Accumulate full multi-part brief from the Bart thread
                await post_message(
                    bart_channel, "📖 Collecting full brief from thread…", thread_ts=thread_ts
                )
                messages = await fetch_thread_messages(bart_channel, thread_ts)
                bart_brief = accumulate_bart_brief(messages, BART_USER_ID) or text

                # Step 2 — Generate brand-compliant SVGs
                image_refs = parse_image_refs(bart_brief)
                svgs: Dict[str, str] = {}
                if image_refs:
                    await post_message(
                        bart_channel,
                        f"🎨 Generating {len(image_refs)} brand-compliant SVG(s)…",
                        thread_ts=thread_ts,
                    )
                    svgs = await generate_svgs(bart_brief, slug)

                # Step 3 — Copywrite + build LP package
                await post_message(
                    bart_channel, "✍️ Step 3/4: Conversion copywriting…", thread_ts=thread_ts
                )
                lp_package = await generate_full_lp(fields, bart_brief, svgs, secondary_keywords, request_id=_request_id(thread_ts))
                final_slug = lp_package["slug"]

                # Step 4 — Commit to GitHub
                files_to_commit: Dict[str, str] = {
                    f"generated-pages/{final_slug}/index.html": lp_package["html"],
                    f"generated-pages/{final_slug}/metadata.json": lp_package["metadata_json"],
                    f"generated-pages/{final_slug}/brief.md": bart_brief,
                }
                for svg_name, svg_content in svgs.items():
                    files_to_commit[f"generated-pages/{final_slug}/images/{svg_name}"] = svg_content
                if LOGO_SVG_BLACK and not LOGO_SVG_BLACK.startswith("[Missing"):
                    files_to_commit[f"generated-pages/{final_slug}/images/dataHub_logo_color_black.svg"] = LOGO_SVG_BLACK

                kit_url = (
                    f"https://github.com/{GITHUB_REPO}/tree/{GITHUB_BRANCH}"
                    f"/generated-pages/{final_slug}"
                )

                if GITHUB_TOKEN and GITHUB_REPO:
                    await post_message(
                        bart_channel, "📤 Committing files to GitHub…", thread_ts=thread_ts
                    )
                    all_ok, failed_paths = await github_commit_files(
                        GITHUB_REPO, files_to_commit,
                        f"Add LP package: {final_slug}", GITHUB_BRANCH,
                    )
                    if all_ok:
                        internal_status = f"✅ Committed to GitHub: {kit_url}"
                    else:
                        internal_status = (
                            f"⚠️ Some files failed to commit:\n"
                            + "\n".join(f"• `{p}`" for p in failed_paths)
                        )
                else:
                    all_ok = False
                    internal_status = "⚠️ GitHub commit skipped — GITHUB_TOKEN or GITHUB_REPO not set"

                # Internal confirmation in the private Bart thread
                await post_message(bart_channel, internal_status, thread_ts=thread_ts)

                # Agency-facing confirmation in #sem-lp-build-kits
                _preview = lp_package.get("pages_url", "")
                agency_msg = (
                    f"✅ *LP package ready*\n"
                    f"*Search term:* {fields['search_term']}\n"
                    f"*Slug:* `{final_slug}`\n"
                    f"*CTA:* {fields.get('primary_cta','Demo')} | "
                    f"*Intent:* {fields.get('intent','Commercial')}\n"
                    f"*Files:* {kit_url}"
                    + (f"\n*Preview:* {_preview}" if _preview else "")
                )
                await post_message(requester_channel, agency_msg)

                job["awaiting"] = "done"
                JOBS[thread_ts] = job
                _save_jobs()

            except Exception as e:
                logger.exception("Pipeline continuation failed: %s", e)
                try:
                    await post_message(bart_channel, f"❌ Pipeline failed: `{e}`", thread_ts=thread_ts)
                    await post_message(requester_channel, f"❌ LP generation failed for `{slug}`: `{e}`")
                except Exception:
                    pass
                job["awaiting"] = "error"
                JOBS[thread_ts] = job
                _save_jobs()

        asyncio.create_task(continue_pipeline())

    return JSONResponse({"ok": True})
